# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TechTatva\'17' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'KWTransition'
  pod 'DZNEmptyDataSet'
  pod 'IQKeyboardManager'
  pod 'Firebase/Core'
  pod 'PBJVideoPlayer'
  pod 'MWPhotoBrowser'

  # Pods for Revels'17

end
